package fr.bretzel.wedit.util;

import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.util.ResourceLocation;
import net.minecraft.util.registry.IRegistry;

public enum Material
{
	AIR("air", new ResourceLocation("minecraft", "air")),
	STONE("stone", new ResourceLocation("minecraft", "stone")),
	GRANITE("granite", new ResourceLocation("minecraft", "granite")),
	POLISHED_GRANITE("polished_granite", new ResourceLocation("minecraft", "polished_granite")),
	DIORITE("diorite", new ResourceLocation("minecraft", "diorite")),
	POLISHED_DIORITE("polished_diorite", new ResourceLocation("minecraft", "polished_diorite")),
	ANDESITE("andesite", new ResourceLocation("minecraft", "andesite")),
	POLISHED_ANDESITE("polished_andesite", new ResourceLocation("minecraft", "polished_andesite")),
	GRASS_BLOCK("grass_block", new ResourceLocation("minecraft", "grass_block")),
	DIRT("dirt", new ResourceLocation("minecraft", "dirt")),
	COARSE_DIRT("coarse_dirt", new ResourceLocation("minecraft", "coarse_dirt")),
	PODZOL("podzol", new ResourceLocation("minecraft", "podzol")),
	COBBLESTONE("cobblestone", new ResourceLocation("minecraft", "cobblestone")),
	OAK_PLANKS("oak_planks", new ResourceLocation("minecraft", "oak_planks")),
	SPRUCE_PLANKS("spruce_planks", new ResourceLocation("minecraft", "spruce_planks")),
	BIRCH_PLANKS("birch_planks", new ResourceLocation("minecraft", "birch_planks")),
	JUNGLE_PLANKS("jungle_planks", new ResourceLocation("minecraft", "jungle_planks")),
	ACACIA_PLANKS("acacia_planks", new ResourceLocation("minecraft", "acacia_planks")),
	DARK_OAK_PLANKS("dark_oak_planks", new ResourceLocation("minecraft", "dark_oak_planks")),
	OAK_SAPLING("oak_sapling", new ResourceLocation("minecraft", "oak_sapling")),
	SPRUCE_SAPLING("spruce_sapling", new ResourceLocation("minecraft", "spruce_sapling")),
	BIRCH_SAPLING("birch_sapling", new ResourceLocation("minecraft", "birch_sapling")),
	JUNGLE_SAPLING("jungle_sapling", new ResourceLocation("minecraft", "jungle_sapling")),
	ACACIA_SAPLING("acacia_sapling", new ResourceLocation("minecraft", "acacia_sapling")),
	DARK_OAK_SAPLING("dark_oak_sapling", new ResourceLocation("minecraft", "dark_oak_sapling")),
	BEDROCK("bedrock", new ResourceLocation("minecraft", "bedrock")),
	WATER("water", new ResourceLocation("minecraft", "water")),
	LAVA("lava", new ResourceLocation("minecraft", "lava")),
	SAND("sand", new ResourceLocation("minecraft", "sand")),
	RED_SAND("red_sand", new ResourceLocation("minecraft", "red_sand")),
	GRAVEL("gravel", new ResourceLocation("minecraft", "gravel")),
	GOLD_ORE("gold_ore", new ResourceLocation("minecraft", "gold_ore")),
	IRON_ORE("iron_ore", new ResourceLocation("minecraft", "iron_ore")),
	COAL_ORE("coal_ore", new ResourceLocation("minecraft", "coal_ore")),
	OAK_LOG("oak_log", new ResourceLocation("minecraft", "oak_log")),
	SPRUCE_LOG("spruce_log", new ResourceLocation("minecraft", "spruce_log")),
	BIRCH_LOG("birch_log", new ResourceLocation("minecraft", "birch_log")),
	JUNGLE_LOG("jungle_log", new ResourceLocation("minecraft", "jungle_log")),
	ACACIA_LOG("acacia_log", new ResourceLocation("minecraft", "acacia_log")),
	DARK_OAK_LOG("dark_oak_log", new ResourceLocation("minecraft", "dark_oak_log")),
	STRIPPED_SPRUCE_LOG("stripped_spruce_log", new ResourceLocation("minecraft", "stripped_spruce_log")),
	STRIPPED_BIRCH_LOG("stripped_birch_log", new ResourceLocation("minecraft", "stripped_birch_log")),
	STRIPPED_JUNGLE_LOG("stripped_jungle_log", new ResourceLocation("minecraft", "stripped_jungle_log")),
	STRIPPED_ACACIA_LOG("stripped_acacia_log", new ResourceLocation("minecraft", "stripped_acacia_log")),
	STRIPPED_DARK_OAK_LOG("stripped_dark_oak_log", new ResourceLocation("minecraft", "stripped_dark_oak_log")),
	STRIPPED_OAK_LOG("stripped_oak_log", new ResourceLocation("minecraft", "stripped_oak_log")),
	OAK_WOOD("oak_wood", new ResourceLocation("minecraft", "oak_wood")),
	SPRUCE_WOOD("spruce_wood", new ResourceLocation("minecraft", "spruce_wood")),
	BIRCH_WOOD("birch_wood", new ResourceLocation("minecraft", "birch_wood")),
	JUNGLE_WOOD("jungle_wood", new ResourceLocation("minecraft", "jungle_wood")),
	ACACIA_WOOD("acacia_wood", new ResourceLocation("minecraft", "acacia_wood")),
	DARK_OAK_WOOD("dark_oak_wood", new ResourceLocation("minecraft", "dark_oak_wood")),
	STRIPPED_OAK_WOOD("stripped_oak_wood", new ResourceLocation("minecraft", "stripped_oak_wood")),
	STRIPPED_SPRUCE_WOOD("stripped_spruce_wood", new ResourceLocation("minecraft", "stripped_spruce_wood")),
	STRIPPED_BIRCH_WOOD("stripped_birch_wood", new ResourceLocation("minecraft", "stripped_birch_wood")),
	STRIPPED_JUNGLE_WOOD("stripped_jungle_wood", new ResourceLocation("minecraft", "stripped_jungle_wood")),
	STRIPPED_ACACIA_WOOD("stripped_acacia_wood", new ResourceLocation("minecraft", "stripped_acacia_wood")),
	STRIPPED_DARK_OAK_WOOD("stripped_dark_oak_wood", new ResourceLocation("minecraft", "stripped_dark_oak_wood")),
	OAK_LEAVES("oak_leaves", new ResourceLocation("minecraft", "oak_leaves")),
	SPRUCE_LEAVES("spruce_leaves", new ResourceLocation("minecraft", "spruce_leaves")),
	BIRCH_LEAVES("birch_leaves", new ResourceLocation("minecraft", "birch_leaves")),
	JUNGLE_LEAVES("jungle_leaves", new ResourceLocation("minecraft", "jungle_leaves")),
	ACACIA_LEAVES("acacia_leaves", new ResourceLocation("minecraft", "acacia_leaves")),
	DARK_OAK_LEAVES("dark_oak_leaves", new ResourceLocation("minecraft", "dark_oak_leaves")),
	SPONGE("sponge", new ResourceLocation("minecraft", "sponge")),
	WET_SPONGE("wet_sponge", new ResourceLocation("minecraft", "wet_sponge")),
	GLASS("glass", new ResourceLocation("minecraft", "glass")),
	LAPIS_ORE("lapis_ore", new ResourceLocation("minecraft", "lapis_ore")),
	LAPIS_BLOCK("lapis_block", new ResourceLocation("minecraft", "lapis_block")),
	DISPENSER("dispenser", new ResourceLocation("minecraft", "dispenser")),
	SANDSTONE("sandstone", new ResourceLocation("minecraft", "sandstone")),
	CHISELED_SANDSTONE("chiseled_sandstone", new ResourceLocation("minecraft", "chiseled_sandstone")),
	CUT_SANDSTONE("cut_sandstone", new ResourceLocation("minecraft", "cut_sandstone")),
	NOTE_BLOCK("note_block", new ResourceLocation("minecraft", "note_block")),
	WHITE_BED("white_bed", new ResourceLocation("minecraft", "white_bed")),
	ORANGE_BED("orange_bed", new ResourceLocation("minecraft", "orange_bed")),
	MAGENTA_BED("magenta_bed", new ResourceLocation("minecraft", "magenta_bed")),
	LIGHT_BLUE_BED("light_blue_bed", new ResourceLocation("minecraft", "light_blue_bed")),
	YELLOW_BED("yellow_bed", new ResourceLocation("minecraft", "yellow_bed")),
	LIME_BED("lime_bed", new ResourceLocation("minecraft", "lime_bed")),
	PINK_BED("pink_bed", new ResourceLocation("minecraft", "pink_bed")),
	GRAY_BED("gray_bed", new ResourceLocation("minecraft", "gray_bed")),
	LIGHT_GRAY_BED("light_gray_bed", new ResourceLocation("minecraft", "light_gray_bed")),
	CYAN_BED("cyan_bed", new ResourceLocation("minecraft", "cyan_bed")),
	PURPLE_BED("purple_bed", new ResourceLocation("minecraft", "purple_bed")),
	BLUE_BED("blue_bed", new ResourceLocation("minecraft", "blue_bed")),
	BROWN_BED("brown_bed", new ResourceLocation("minecraft", "brown_bed")),
	GREEN_BED("green_bed", new ResourceLocation("minecraft", "green_bed")),
	RED_BED("red_bed", new ResourceLocation("minecraft", "red_bed")),
	BLACK_BED("black_bed", new ResourceLocation("minecraft", "black_bed")),
	POWERED_RAIL("powered_rail", new ResourceLocation("minecraft", "powered_rail")),
	DETECTOR_RAIL("detector_rail", new ResourceLocation("minecraft", "detector_rail")),
	STICKY_PISTON("sticky_piston", new ResourceLocation("minecraft", "sticky_piston")),
	COBWEB("cobweb", new ResourceLocation("minecraft", "cobweb")),
	GRASS("grass", new ResourceLocation("minecraft", "grass")),
	FERN("fern", new ResourceLocation("minecraft", "fern")),
	DEAD_BUSH("dead_bush", new ResourceLocation("minecraft", "dead_bush")),
	SEAGRASS("seagrass", new ResourceLocation("minecraft", "seagrass")),
	TALL_SEAGRASS("tall_seagrass", new ResourceLocation("minecraft", "tall_seagrass")),
	PISTON("piston", new ResourceLocation("minecraft", "piston")),
	PISTON_HEAD("piston_head", new ResourceLocation("minecraft", "piston_head")),
	WHITE_WOOL("white_wool", new ResourceLocation("minecraft", "white_wool")),
	ORANGE_WOOL("orange_wool", new ResourceLocation("minecraft", "orange_wool")),
	MAGENTA_WOOL("magenta_wool", new ResourceLocation("minecraft", "magenta_wool")),
	LIGHT_BLUE_WOOL("light_blue_wool", new ResourceLocation("minecraft", "light_blue_wool")),
	YELLOW_WOOL("yellow_wool", new ResourceLocation("minecraft", "yellow_wool")),
	LIME_WOOL("lime_wool", new ResourceLocation("minecraft", "lime_wool")),
	PINK_WOOL("pink_wool", new ResourceLocation("minecraft", "pink_wool")),
	GRAY_WOOL("gray_wool", new ResourceLocation("minecraft", "gray_wool")),
	LIGHT_GRAY_WOOL("light_gray_wool", new ResourceLocation("minecraft", "light_gray_wool")),
	CYAN_WOOL("cyan_wool", new ResourceLocation("minecraft", "cyan_wool")),
	PURPLE_WOOL("purple_wool", new ResourceLocation("minecraft", "purple_wool")),
	BLUE_WOOL("blue_wool", new ResourceLocation("minecraft", "blue_wool")),
	BROWN_WOOL("brown_wool", new ResourceLocation("minecraft", "brown_wool")),
	GREEN_WOOL("green_wool", new ResourceLocation("minecraft", "green_wool")),
	RED_WOOL("red_wool", new ResourceLocation("minecraft", "red_wool")),
	BLACK_WOOL("black_wool", new ResourceLocation("minecraft", "black_wool")),
	MOVING_PISTON("moving_piston", new ResourceLocation("minecraft", "moving_piston")),
	DANDELION("dandelion", new ResourceLocation("minecraft", "dandelion")),
	POPPY("poppy", new ResourceLocation("minecraft", "poppy")),
	BLUE_ORCHID("blue_orchid", new ResourceLocation("minecraft", "blue_orchid")),
	ALLIUM("allium", new ResourceLocation("minecraft", "allium")),
	AZURE_BLUET("azure_bluet", new ResourceLocation("minecraft", "azure_bluet")),
	RED_TULIP("red_tulip", new ResourceLocation("minecraft", "red_tulip")),
	ORANGE_TULIP("orange_tulip", new ResourceLocation("minecraft", "orange_tulip")),
	WHITE_TULIP("white_tulip", new ResourceLocation("minecraft", "white_tulip")),
	PINK_TULIP("pink_tulip", new ResourceLocation("minecraft", "pink_tulip")),
	OXEYE_DAISY("oxeye_daisy", new ResourceLocation("minecraft", "oxeye_daisy")),
	BROWN_MUSHROOM("brown_mushroom", new ResourceLocation("minecraft", "brown_mushroom")),
	RED_MUSHROOM("red_mushroom", new ResourceLocation("minecraft", "red_mushroom")),
	GOLD_BLOCK("gold_block", new ResourceLocation("minecraft", "gold_block")),
	IRON_BLOCK("iron_block", new ResourceLocation("minecraft", "iron_block")),
	BRICKS("bricks", new ResourceLocation("minecraft", "bricks")),
	TNT("tnt", new ResourceLocation("minecraft", "tnt")),
	BOOKSHELF("bookshelf", new ResourceLocation("minecraft", "bookshelf")),
	MOSSY_COBBLESTONE("mossy_cobblestone", new ResourceLocation("minecraft", "mossy_cobblestone")),
	OBSIDIAN("obsidian", new ResourceLocation("minecraft", "obsidian")),
	TORCH("torch", new ResourceLocation("minecraft", "torch")),
	WALL_TORCH("wall_torch", new ResourceLocation("minecraft", "wall_torch")),
	FIRE("fire", new ResourceLocation("minecraft", "fire")),
	SPAWNER("spawner", new ResourceLocation("minecraft", "spawner")),
	OAK_STAIRS("oak_stairs", new ResourceLocation("minecraft", "oak_stairs")),
	CHEST("chest", new ResourceLocation("minecraft", "chest")),
	REDSTONE_WIRE("redstone_wire", new ResourceLocation("minecraft", "redstone_wire")),
	DIAMOND_ORE("diamond_ore", new ResourceLocation("minecraft", "diamond_ore")),
	DIAMOND_BLOCK("diamond_block", new ResourceLocation("minecraft", "diamond_block")),
	CRAFTING_TABLE("crafting_table", new ResourceLocation("minecraft", "crafting_table")),
	WHEAT("wheat", new ResourceLocation("minecraft", "wheat")),
	FARMLAND("farmland", new ResourceLocation("minecraft", "farmland")),
	FURNACE("furnace", new ResourceLocation("minecraft", "furnace")),
	SIGN("sign", new ResourceLocation("minecraft", "sign")),
	OAK_DOOR("oak_door", new ResourceLocation("minecraft", "oak_door")),
	LADDER("ladder", new ResourceLocation("minecraft", "ladder")),
	RAIL("rail", new ResourceLocation("minecraft", "rail")),
	COBBLESTONE_STAIRS("cobblestone_stairs", new ResourceLocation("minecraft", "cobblestone_stairs")),
	WALL_SIGN("wall_sign", new ResourceLocation("minecraft", "wall_sign")),
	LEVER("lever", new ResourceLocation("minecraft", "lever")),
	STONE_PRESSURE_PLATE("stone_pressure_plate", new ResourceLocation("minecraft", "stone_pressure_plate")),
	IRON_DOOR("iron_door", new ResourceLocation("minecraft", "iron_door")),
	OAK_PRESSURE_PLATE("oak_pressure_plate", new ResourceLocation("minecraft", "oak_pressure_plate")),
	SPRUCE_PRESSURE_PLATE("spruce_pressure_plate", new ResourceLocation("minecraft", "spruce_pressure_plate")),
	BIRCH_PRESSURE_PLATE("birch_pressure_plate", new ResourceLocation("minecraft", "birch_pressure_plate")),
	JUNGLE_PRESSURE_PLATE("jungle_pressure_plate", new ResourceLocation("minecraft", "jungle_pressure_plate")),
	ACACIA_PRESSURE_PLATE("acacia_pressure_plate", new ResourceLocation("minecraft", "acacia_pressure_plate")),
	DARK_OAK_PRESSURE_PLATE("dark_oak_pressure_plate", new ResourceLocation("minecraft", "dark_oak_pressure_plate")),
	REDSTONE_ORE("redstone_ore", new ResourceLocation("minecraft", "redstone_ore")),
	REDSTONE_TORCH("redstone_torch", new ResourceLocation("minecraft", "redstone_torch")),
	REDSTONE_WALL_TORCH("redstone_wall_torch", new ResourceLocation("minecraft", "redstone_wall_torch")),
	STONE_BUTTON("stone_button", new ResourceLocation("minecraft", "stone_button")),
	SNOW("snow", new ResourceLocation("minecraft", "snow")),
	ICE("ice", new ResourceLocation("minecraft", "ice")),
	SNOW_BLOCK("snow_block", new ResourceLocation("minecraft", "snow_block")),
	CACTUS("cactus", new ResourceLocation("minecraft", "cactus")),
	CLAY("clay", new ResourceLocation("minecraft", "clay")),
	SUGAR_CANE("sugar_cane", new ResourceLocation("minecraft", "sugar_cane")),
	JUKEBOX("jukebox", new ResourceLocation("minecraft", "jukebox")),
	OAK_FENCE("oak_fence", new ResourceLocation("minecraft", "oak_fence")),
	PUMPKIN("pumpkin", new ResourceLocation("minecraft", "pumpkin")),
	NETHERRACK("netherrack", new ResourceLocation("minecraft", "netherrack")),
	SOUL_SAND("soul_sand", new ResourceLocation("minecraft", "soul_sand")),
	GLOWSTONE("glowstone", new ResourceLocation("minecraft", "glowstone")),
	NETHER_PORTAL("nether_portal", new ResourceLocation("minecraft", "nether_portal")),
	CARVED_PUMPKIN("carved_pumpkin", new ResourceLocation("minecraft", "carved_pumpkin")),
	JACK_O_LANTERN("jack_o_lantern", new ResourceLocation("minecraft", "jack_o_lantern")),
	CAKE("cake", new ResourceLocation("minecraft", "cake")),
	REPEATER("repeater", new ResourceLocation("minecraft", "repeater")),
	WHITE_STAINED_GLASS("white_stained_glass", new ResourceLocation("minecraft", "white_stained_glass")),
	ORANGE_STAINED_GLASS("orange_stained_glass", new ResourceLocation("minecraft", "orange_stained_glass")),
	MAGENTA_STAINED_GLASS("magenta_stained_glass", new ResourceLocation("minecraft", "magenta_stained_glass")),
	LIGHT_BLUE_STAINED_GLASS("light_blue_stained_glass", new ResourceLocation("minecraft", "light_blue_stained_glass")),
	YELLOW_STAINED_GLASS("yellow_stained_glass", new ResourceLocation("minecraft", "yellow_stained_glass")),
	LIME_STAINED_GLASS("lime_stained_glass", new ResourceLocation("minecraft", "lime_stained_glass")),
	PINK_STAINED_GLASS("pink_stained_glass", new ResourceLocation("minecraft", "pink_stained_glass")),
	GRAY_STAINED_GLASS("gray_stained_glass", new ResourceLocation("minecraft", "gray_stained_glass")),
	LIGHT_GRAY_STAINED_GLASS("light_gray_stained_glass", new ResourceLocation("minecraft", "light_gray_stained_glass")),
	CYAN_STAINED_GLASS("cyan_stained_glass", new ResourceLocation("minecraft", "cyan_stained_glass")),
	PURPLE_STAINED_GLASS("purple_stained_glass", new ResourceLocation("minecraft", "purple_stained_glass")),
	BLUE_STAINED_GLASS("blue_stained_glass", new ResourceLocation("minecraft", "blue_stained_glass")),
	BROWN_STAINED_GLASS("brown_stained_glass", new ResourceLocation("minecraft", "brown_stained_glass")),
	GREEN_STAINED_GLASS("green_stained_glass", new ResourceLocation("minecraft", "green_stained_glass")),
	RED_STAINED_GLASS("red_stained_glass", new ResourceLocation("minecraft", "red_stained_glass")),
	BLACK_STAINED_GLASS("black_stained_glass", new ResourceLocation("minecraft", "black_stained_glass")),
	OAK_TRAPDOOR("oak_trapdoor", new ResourceLocation("minecraft", "oak_trapdoor")),
	SPRUCE_TRAPDOOR("spruce_trapdoor", new ResourceLocation("minecraft", "spruce_trapdoor")),
	BIRCH_TRAPDOOR("birch_trapdoor", new ResourceLocation("minecraft", "birch_trapdoor")),
	JUNGLE_TRAPDOOR("jungle_trapdoor", new ResourceLocation("minecraft", "jungle_trapdoor")),
	ACACIA_TRAPDOOR("acacia_trapdoor", new ResourceLocation("minecraft", "acacia_trapdoor")),
	DARK_OAK_TRAPDOOR("dark_oak_trapdoor", new ResourceLocation("minecraft", "dark_oak_trapdoor")),
	INFESTED_STONE("infested_stone", new ResourceLocation("minecraft", "infested_stone")),
	INFESTED_COBBLESTONE("infested_cobblestone", new ResourceLocation("minecraft", "infested_cobblestone")),
	INFESTED_STONE_BRICKS("infested_stone_bricks", new ResourceLocation("minecraft", "infested_stone_bricks")),
	INFESTED_MOSSY_STONE_BRICKS("infested_mossy_stone_bricks", new ResourceLocation("minecraft", "infested_mossy_stone_bricks")),
	INFESTED_CRACKED_STONE_BRICKS("infested_cracked_stone_bricks", new ResourceLocation("minecraft", "infested_cracked_stone_bricks")),
	INFESTED_CHISELED_STONE_BRICKS("infested_chiseled_stone_bricks", new ResourceLocation("minecraft", "infested_chiseled_stone_bricks")),
	STONE_BRICKS("stone_bricks", new ResourceLocation("minecraft", "stone_bricks")),
	MOSSY_STONE_BRICKS("mossy_stone_bricks", new ResourceLocation("minecraft", "mossy_stone_bricks")),
	CRACKED_STONE_BRICKS("cracked_stone_bricks", new ResourceLocation("minecraft", "cracked_stone_bricks")),
	CHISELED_STONE_BRICKS("chiseled_stone_bricks", new ResourceLocation("minecraft", "chiseled_stone_bricks")),
	BROWN_MUSHROOM_BLOCK("brown_mushroom_block", new ResourceLocation("minecraft", "brown_mushroom_block")),
	RED_MUSHROOM_BLOCK("red_mushroom_block", new ResourceLocation("minecraft", "red_mushroom_block")),
	MUSHROOM_STEM("mushroom_stem", new ResourceLocation("minecraft", "mushroom_stem")),
	IRON_BARS("iron_bars", new ResourceLocation("minecraft", "iron_bars")),
	GLASS_PANE("glass_pane", new ResourceLocation("minecraft", "glass_pane")),
	MELON("melon", new ResourceLocation("minecraft", "melon")),
	ATTACHED_PUMPKIN_STEM("attached_pumpkin_stem", new ResourceLocation("minecraft", "attached_pumpkin_stem")),
	ATTACHED_MELON_STEM("attached_melon_stem", new ResourceLocation("minecraft", "attached_melon_stem")),
	PUMPKIN_STEM("pumpkin_stem", new ResourceLocation("minecraft", "pumpkin_stem")),
	MELON_STEM("melon_stem", new ResourceLocation("minecraft", "melon_stem")),
	VINE("vine", new ResourceLocation("minecraft", "vine")),
	OAK_FENCE_GATE("oak_fence_gate", new ResourceLocation("minecraft", "oak_fence_gate")),
	BRICK_STAIRS("brick_stairs", new ResourceLocation("minecraft", "brick_stairs")),
	STONE_BRICK_STAIRS("stone_brick_stairs", new ResourceLocation("minecraft", "stone_brick_stairs")),
	MYCELIUM("mycelium", new ResourceLocation("minecraft", "mycelium")),
	LILY_PAD("lily_pad", new ResourceLocation("minecraft", "lily_pad")),
	NETHER_BRICKS("nether_bricks", new ResourceLocation("minecraft", "nether_bricks")),
	NETHER_BRICK_FENCE("nether_brick_fence", new ResourceLocation("minecraft", "nether_brick_fence")),
	NETHER_BRICK_STAIRS("nether_brick_stairs", new ResourceLocation("minecraft", "nether_brick_stairs")),
	NETHER_WART("nether_wart", new ResourceLocation("minecraft", "nether_wart")),
	ENCHANTING_TABLE("enchanting_table", new ResourceLocation("minecraft", "enchanting_table")),
	BREWING_STAND("brewing_stand", new ResourceLocation("minecraft", "brewing_stand")),
	CAULDRON("cauldron", new ResourceLocation("minecraft", "cauldron")),
	END_PORTAL("end_portal", new ResourceLocation("minecraft", "end_portal")),
	END_PORTAL_FRAME("end_portal_frame", new ResourceLocation("minecraft", "end_portal_frame")),
	END_STONE("end_stone", new ResourceLocation("minecraft", "end_stone")),
	DRAGON_EGG("dragon_egg", new ResourceLocation("minecraft", "dragon_egg")),
	REDSTONE_LAMP("redstone_lamp", new ResourceLocation("minecraft", "redstone_lamp")),
	COCOA("cocoa", new ResourceLocation("minecraft", "cocoa")),
	SANDSTONE_STAIRS("sandstone_stairs", new ResourceLocation("minecraft", "sandstone_stairs")),
	EMERALD_ORE("emerald_ore", new ResourceLocation("minecraft", "emerald_ore")),
	ENDER_CHEST("ender_chest", new ResourceLocation("minecraft", "ender_chest")),
	TRIPWIRE_HOOK("tripwire_hook", new ResourceLocation("minecraft", "tripwire_hook")),
	TRIPWIRE("tripwire", new ResourceLocation("minecraft", "tripwire")),
	EMERALD_BLOCK("emerald_block", new ResourceLocation("minecraft", "emerald_block")),
	SPRUCE_STAIRS("spruce_stairs", new ResourceLocation("minecraft", "spruce_stairs")),
	BIRCH_STAIRS("birch_stairs", new ResourceLocation("minecraft", "birch_stairs")),
	JUNGLE_STAIRS("jungle_stairs", new ResourceLocation("minecraft", "jungle_stairs")),
	COMMAND_BLOCK("command_block", new ResourceLocation("minecraft", "command_block")),
	BEACON("beacon", new ResourceLocation("minecraft", "beacon")),
	COBBLESTONE_WALL("cobblestone_wall", new ResourceLocation("minecraft", "cobblestone_wall")),
	MOSSY_COBBLESTONE_WALL("mossy_cobblestone_wall", new ResourceLocation("minecraft", "mossy_cobblestone_wall")),
	FLOWER_POT("flower_pot", new ResourceLocation("minecraft", "flower_pot")),
	POTTED_OAK_SAPLING("potted_oak_sapling", new ResourceLocation("minecraft", "potted_oak_sapling")),
	POTTED_SPRUCE_SAPLING("potted_spruce_sapling", new ResourceLocation("minecraft", "potted_spruce_sapling")),
	POTTED_BIRCH_SAPLING("potted_birch_sapling", new ResourceLocation("minecraft", "potted_birch_sapling")),
	POTTED_JUNGLE_SAPLING("potted_jungle_sapling", new ResourceLocation("minecraft", "potted_jungle_sapling")),
	POTTED_ACACIA_SAPLING("potted_acacia_sapling", new ResourceLocation("minecraft", "potted_acacia_sapling")),
	POTTED_DARK_OAK_SAPLING("potted_dark_oak_sapling", new ResourceLocation("minecraft", "potted_dark_oak_sapling")),
	POTTED_FERN("potted_fern", new ResourceLocation("minecraft", "potted_fern")),
	POTTED_DANDELION("potted_dandelion", new ResourceLocation("minecraft", "potted_dandelion")),
	POTTED_POPPY("potted_poppy", new ResourceLocation("minecraft", "potted_poppy")),
	POTTED_BLUE_ORCHID("potted_blue_orchid", new ResourceLocation("minecraft", "potted_blue_orchid")),
	POTTED_ALLIUM("potted_allium", new ResourceLocation("minecraft", "potted_allium")),
	POTTED_AZURE_BLUET("potted_azure_bluet", new ResourceLocation("minecraft", "potted_azure_bluet")),
	POTTED_RED_TULIP("potted_red_tulip", new ResourceLocation("minecraft", "potted_red_tulip")),
	POTTED_ORANGE_TULIP("potted_orange_tulip", new ResourceLocation("minecraft", "potted_orange_tulip")),
	POTTED_WHITE_TULIP("potted_white_tulip", new ResourceLocation("minecraft", "potted_white_tulip")),
	POTTED_PINK_TULIP("potted_pink_tulip", new ResourceLocation("minecraft", "potted_pink_tulip")),
	POTTED_OXEYE_DAISY("potted_oxeye_daisy", new ResourceLocation("minecraft", "potted_oxeye_daisy")),
	POTTED_RED_MUSHROOM("potted_red_mushroom", new ResourceLocation("minecraft", "potted_red_mushroom")),
	POTTED_BROWN_MUSHROOM("potted_brown_mushroom", new ResourceLocation("minecraft", "potted_brown_mushroom")),
	POTTED_DEAD_BUSH("potted_dead_bush", new ResourceLocation("minecraft", "potted_dead_bush")),
	POTTED_CACTUS("potted_cactus", new ResourceLocation("minecraft", "potted_cactus")),
	CARROTS("carrots", new ResourceLocation("minecraft", "carrots")),
	POTATOES("potatoes", new ResourceLocation("minecraft", "potatoes")),
	OAK_BUTTON("oak_button", new ResourceLocation("minecraft", "oak_button")),
	SPRUCE_BUTTON("spruce_button", new ResourceLocation("minecraft", "spruce_button")),
	BIRCH_BUTTON("birch_button", new ResourceLocation("minecraft", "birch_button")),
	JUNGLE_BUTTON("jungle_button", new ResourceLocation("minecraft", "jungle_button")),
	ACACIA_BUTTON("acacia_button", new ResourceLocation("minecraft", "acacia_button")),
	DARK_OAK_BUTTON("dark_oak_button", new ResourceLocation("minecraft", "dark_oak_button")),
	SKELETON_WALL_SKULL("skeleton_wall_skull", new ResourceLocation("minecraft", "skeleton_wall_skull")),
	SKELETON_SKULL("skeleton_skull", new ResourceLocation("minecraft", "skeleton_skull")),
	WITHER_SKELETON_WALL_SKULL("wither_skeleton_wall_skull", new ResourceLocation("minecraft", "wither_skeleton_wall_skull")),
	WITHER_SKELETON_SKULL("wither_skeleton_skull", new ResourceLocation("minecraft", "wither_skeleton_skull")),
	ZOMBIE_WALL_HEAD("zombie_wall_head", new ResourceLocation("minecraft", "zombie_wall_head")),
	ZOMBIE_HEAD("zombie_head", new ResourceLocation("minecraft", "zombie_head")),
	PLAYER_WALL_HEAD("player_wall_head", new ResourceLocation("minecraft", "player_wall_head")),
	PLAYER_HEAD("player_head", new ResourceLocation("minecraft", "player_head")),
	CREEPER_WALL_HEAD("creeper_wall_head", new ResourceLocation("minecraft", "creeper_wall_head")),
	CREEPER_HEAD("creeper_head", new ResourceLocation("minecraft", "creeper_head")),
	DRAGON_WALL_HEAD("dragon_wall_head", new ResourceLocation("minecraft", "dragon_wall_head")),
	DRAGON_HEAD("dragon_head", new ResourceLocation("minecraft", "dragon_head")),
	ANVIL("anvil", new ResourceLocation("minecraft", "anvil")),
	CHIPPED_ANVIL("chipped_anvil", new ResourceLocation("minecraft", "chipped_anvil")),
	DAMAGED_ANVIL("damaged_anvil", new ResourceLocation("minecraft", "damaged_anvil")),
	TRAPPED_CHEST("trapped_chest", new ResourceLocation("minecraft", "trapped_chest")),
	LIGHT_WEIGHTED_PRESSURE_PLATE("light_weighted_pressure_plate", new ResourceLocation("minecraft", "light_weighted_pressure_plate")),
	HEAVY_WEIGHTED_PRESSURE_PLATE("heavy_weighted_pressure_plate", new ResourceLocation("minecraft", "heavy_weighted_pressure_plate")),
	COMPARATOR("comparator", new ResourceLocation("minecraft", "comparator")),
	DAYLIGHT_DETECTOR("daylight_detector", new ResourceLocation("minecraft", "daylight_detector")),
	REDSTONE_BLOCK("redstone_block", new ResourceLocation("minecraft", "redstone_block")),
	NETHER_QUARTZ_ORE("nether_quartz_ore", new ResourceLocation("minecraft", "nether_quartz_ore")),
	HOPPER("hopper", new ResourceLocation("minecraft", "hopper")),
	QUARTZ_BLOCK("quartz_block", new ResourceLocation("minecraft", "quartz_block")),
	CHISELED_QUARTZ_BLOCK("chiseled_quartz_block", new ResourceLocation("minecraft", "chiseled_quartz_block")),
	QUARTZ_PILLAR("quartz_pillar", new ResourceLocation("minecraft", "quartz_pillar")),
	QUARTZ_STAIRS("quartz_stairs", new ResourceLocation("minecraft", "quartz_stairs")),
	ACTIVATOR_RAIL("activator_rail", new ResourceLocation("minecraft", "activator_rail")),
	DROPPER("dropper", new ResourceLocation("minecraft", "dropper")),
	WHITE_TERRACOTTA("white_terracotta", new ResourceLocation("minecraft", "white_terracotta")),
	ORANGE_TERRACOTTA("orange_terracotta", new ResourceLocation("minecraft", "orange_terracotta")),
	MAGENTA_TERRACOTTA("magenta_terracotta", new ResourceLocation("minecraft", "magenta_terracotta")),
	LIGHT_BLUE_TERRACOTTA("light_blue_terracotta", new ResourceLocation("minecraft", "light_blue_terracotta")),
	YELLOW_TERRACOTTA("yellow_terracotta", new ResourceLocation("minecraft", "yellow_terracotta")),
	LIME_TERRACOTTA("lime_terracotta", new ResourceLocation("minecraft", "lime_terracotta")),
	PINK_TERRACOTTA("pink_terracotta", new ResourceLocation("minecraft", "pink_terracotta")),
	GRAY_TERRACOTTA("gray_terracotta", new ResourceLocation("minecraft", "gray_terracotta")),
	LIGHT_GRAY_TERRACOTTA("light_gray_terracotta", new ResourceLocation("minecraft", "light_gray_terracotta")),
	CYAN_TERRACOTTA("cyan_terracotta", new ResourceLocation("minecraft", "cyan_terracotta")),
	PURPLE_TERRACOTTA("purple_terracotta", new ResourceLocation("minecraft", "purple_terracotta")),
	BLUE_TERRACOTTA("blue_terracotta", new ResourceLocation("minecraft", "blue_terracotta")),
	BROWN_TERRACOTTA("brown_terracotta", new ResourceLocation("minecraft", "brown_terracotta")),
	GREEN_TERRACOTTA("green_terracotta", new ResourceLocation("minecraft", "green_terracotta")),
	RED_TERRACOTTA("red_terracotta", new ResourceLocation("minecraft", "red_terracotta")),
	BLACK_TERRACOTTA("black_terracotta", new ResourceLocation("minecraft", "black_terracotta")),
	WHITE_STAINED_GLASS_PANE("white_stained_glass_pane", new ResourceLocation("minecraft", "white_stained_glass_pane")),
	ORANGE_STAINED_GLASS_PANE("orange_stained_glass_pane", new ResourceLocation("minecraft", "orange_stained_glass_pane")),
	MAGENTA_STAINED_GLASS_PANE("magenta_stained_glass_pane", new ResourceLocation("minecraft", "magenta_stained_glass_pane")),
	LIGHT_BLUE_STAINED_GLASS_PANE("light_blue_stained_glass_pane", new ResourceLocation("minecraft", "light_blue_stained_glass_pane")),
	YELLOW_STAINED_GLASS_PANE("yellow_stained_glass_pane", new ResourceLocation("minecraft", "yellow_stained_glass_pane")),
	LIME_STAINED_GLASS_PANE("lime_stained_glass_pane", new ResourceLocation("minecraft", "lime_stained_glass_pane")),
	PINK_STAINED_GLASS_PANE("pink_stained_glass_pane", new ResourceLocation("minecraft", "pink_stained_glass_pane")),
	GRAY_STAINED_GLASS_PANE("gray_stained_glass_pane", new ResourceLocation("minecraft", "gray_stained_glass_pane")),
	LIGHT_GRAY_STAINED_GLASS_PANE("light_gray_stained_glass_pane", new ResourceLocation("minecraft", "light_gray_stained_glass_pane")),
	CYAN_STAINED_GLASS_PANE("cyan_stained_glass_pane", new ResourceLocation("minecraft", "cyan_stained_glass_pane")),
	PURPLE_STAINED_GLASS_PANE("purple_stained_glass_pane", new ResourceLocation("minecraft", "purple_stained_glass_pane")),
	BLUE_STAINED_GLASS_PANE("blue_stained_glass_pane", new ResourceLocation("minecraft", "blue_stained_glass_pane")),
	BROWN_STAINED_GLASS_PANE("brown_stained_glass_pane", new ResourceLocation("minecraft", "brown_stained_glass_pane")),
	GREEN_STAINED_GLASS_PANE("green_stained_glass_pane", new ResourceLocation("minecraft", "green_stained_glass_pane")),
	RED_STAINED_GLASS_PANE("red_stained_glass_pane", new ResourceLocation("minecraft", "red_stained_glass_pane")),
	BLACK_STAINED_GLASS_PANE("black_stained_glass_pane", new ResourceLocation("minecraft", "black_stained_glass_pane")),
	ACACIA_STAIRS("acacia_stairs", new ResourceLocation("minecraft", "acacia_stairs")),
	DARK_OAK_STAIRS("dark_oak_stairs", new ResourceLocation("minecraft", "dark_oak_stairs")),
	SLIME_BLOCK("slime_block", new ResourceLocation("minecraft", "slime_block")),
	BARRIER("barrier", new ResourceLocation("minecraft", "barrier")),
	IRON_TRAPDOOR("iron_trapdoor", new ResourceLocation("minecraft", "iron_trapdoor")),
	PRISMARINE("prismarine", new ResourceLocation("minecraft", "prismarine")),
	PRISMARINE_BRICKS("prismarine_bricks", new ResourceLocation("minecraft", "prismarine_bricks")),
	DARK_PRISMARINE("dark_prismarine", new ResourceLocation("minecraft", "dark_prismarine")),
	PRISMARINE_STAIRS("prismarine_stairs", new ResourceLocation("minecraft", "prismarine_stairs")),
	PRISMARINE_BRICK_STAIRS("prismarine_brick_stairs", new ResourceLocation("minecraft", "prismarine_brick_stairs")),
	DARK_PRISMARINE_STAIRS("dark_prismarine_stairs", new ResourceLocation("minecraft", "dark_prismarine_stairs")),
	PRISMARINE_SLAB("prismarine_slab", new ResourceLocation("minecraft", "prismarine_slab")),
	PRISMARINE_BRICK_SLAB("prismarine_brick_slab", new ResourceLocation("minecraft", "prismarine_brick_slab")),
	DARK_PRISMARINE_SLAB("dark_prismarine_slab", new ResourceLocation("minecraft", "dark_prismarine_slab")),
	SEA_LANTERN("sea_lantern", new ResourceLocation("minecraft", "sea_lantern")),
	HAY_BLOCK("hay_block", new ResourceLocation("minecraft", "hay_block")),
	WHITE_CARPET("white_carpet", new ResourceLocation("minecraft", "white_carpet")),
	ORANGE_CARPET("orange_carpet", new ResourceLocation("minecraft", "orange_carpet")),
	MAGENTA_CARPET("magenta_carpet", new ResourceLocation("minecraft", "magenta_carpet")),
	LIGHT_BLUE_CARPET("light_blue_carpet", new ResourceLocation("minecraft", "light_blue_carpet")),
	YELLOW_CARPET("yellow_carpet", new ResourceLocation("minecraft", "yellow_carpet")),
	LIME_CARPET("lime_carpet", new ResourceLocation("minecraft", "lime_carpet")),
	PINK_CARPET("pink_carpet", new ResourceLocation("minecraft", "pink_carpet")),
	GRAY_CARPET("gray_carpet", new ResourceLocation("minecraft", "gray_carpet")),
	LIGHT_GRAY_CARPET("light_gray_carpet", new ResourceLocation("minecraft", "light_gray_carpet")),
	CYAN_CARPET("cyan_carpet", new ResourceLocation("minecraft", "cyan_carpet")),
	PURPLE_CARPET("purple_carpet", new ResourceLocation("minecraft", "purple_carpet")),
	BLUE_CARPET("blue_carpet", new ResourceLocation("minecraft", "blue_carpet")),
	BROWN_CARPET("brown_carpet", new ResourceLocation("minecraft", "brown_carpet")),
	GREEN_CARPET("green_carpet", new ResourceLocation("minecraft", "green_carpet")),
	RED_CARPET("red_carpet", new ResourceLocation("minecraft", "red_carpet")),
	BLACK_CARPET("black_carpet", new ResourceLocation("minecraft", "black_carpet")),
	TERRACOTTA("terracotta", new ResourceLocation("minecraft", "terracotta")),
	COAL_BLOCK("coal_block", new ResourceLocation("minecraft", "coal_block")),
	PACKED_ICE("packed_ice", new ResourceLocation("minecraft", "packed_ice")),
	SUNFLOWER("sunflower", new ResourceLocation("minecraft", "sunflower")),
	LILAC("lilac", new ResourceLocation("minecraft", "lilac")),
	ROSE_BUSH("rose_bush", new ResourceLocation("minecraft", "rose_bush")),
	PEONY("peony", new ResourceLocation("minecraft", "peony")),
	TALL_GRASS("tall_grass", new ResourceLocation("minecraft", "tall_grass")),
	LARGE_FERN("large_fern", new ResourceLocation("minecraft", "large_fern")),
	WHITE_BANNER("white_banner", new ResourceLocation("minecraft", "white_banner")),
	ORANGE_BANNER("orange_banner", new ResourceLocation("minecraft", "orange_banner")),
	MAGENTA_BANNER("magenta_banner", new ResourceLocation("minecraft", "magenta_banner")),
	LIGHT_BLUE_BANNER("light_blue_banner", new ResourceLocation("minecraft", "light_blue_banner")),
	YELLOW_BANNER("yellow_banner", new ResourceLocation("minecraft", "yellow_banner")),
	LIME_BANNER("lime_banner", new ResourceLocation("minecraft", "lime_banner")),
	PINK_BANNER("pink_banner", new ResourceLocation("minecraft", "pink_banner")),
	GRAY_BANNER("gray_banner", new ResourceLocation("minecraft", "gray_banner")),
	LIGHT_GRAY_BANNER("light_gray_banner", new ResourceLocation("minecraft", "light_gray_banner")),
	CYAN_BANNER("cyan_banner", new ResourceLocation("minecraft", "cyan_banner")),
	PURPLE_BANNER("purple_banner", new ResourceLocation("minecraft", "purple_banner")),
	BLUE_BANNER("blue_banner", new ResourceLocation("minecraft", "blue_banner")),
	BROWN_BANNER("brown_banner", new ResourceLocation("minecraft", "brown_banner")),
	GREEN_BANNER("green_banner", new ResourceLocation("minecraft", "green_banner")),
	RED_BANNER("red_banner", new ResourceLocation("minecraft", "red_banner")),
	BLACK_BANNER("black_banner", new ResourceLocation("minecraft", "black_banner")),
	WHITE_WALL_BANNER("white_wall_banner", new ResourceLocation("minecraft", "white_wall_banner")),
	ORANGE_WALL_BANNER("orange_wall_banner", new ResourceLocation("minecraft", "orange_wall_banner")),
	MAGENTA_WALL_BANNER("magenta_wall_banner", new ResourceLocation("minecraft", "magenta_wall_banner")),
	LIGHT_BLUE_WALL_BANNER("light_blue_wall_banner", new ResourceLocation("minecraft", "light_blue_wall_banner")),
	YELLOW_WALL_BANNER("yellow_wall_banner", new ResourceLocation("minecraft", "yellow_wall_banner")),
	LIME_WALL_BANNER("lime_wall_banner", new ResourceLocation("minecraft", "lime_wall_banner")),
	PINK_WALL_BANNER("pink_wall_banner", new ResourceLocation("minecraft", "pink_wall_banner")),
	GRAY_WALL_BANNER("gray_wall_banner", new ResourceLocation("minecraft", "gray_wall_banner")),
	LIGHT_GRAY_WALL_BANNER("light_gray_wall_banner", new ResourceLocation("minecraft", "light_gray_wall_banner")),
	CYAN_WALL_BANNER("cyan_wall_banner", new ResourceLocation("minecraft", "cyan_wall_banner")),
	PURPLE_WALL_BANNER("purple_wall_banner", new ResourceLocation("minecraft", "purple_wall_banner")),
	BLUE_WALL_BANNER("blue_wall_banner", new ResourceLocation("minecraft", "blue_wall_banner")),
	BROWN_WALL_BANNER("brown_wall_banner", new ResourceLocation("minecraft", "brown_wall_banner")),
	GREEN_WALL_BANNER("green_wall_banner", new ResourceLocation("minecraft", "green_wall_banner")),
	RED_WALL_BANNER("red_wall_banner", new ResourceLocation("minecraft", "red_wall_banner")),
	BLACK_WALL_BANNER("black_wall_banner", new ResourceLocation("minecraft", "black_wall_banner")),
	RED_SANDSTONE("red_sandstone", new ResourceLocation("minecraft", "red_sandstone")),
	CHISELED_RED_SANDSTONE("chiseled_red_sandstone", new ResourceLocation("minecraft", "chiseled_red_sandstone")),
	CUT_RED_SANDSTONE("cut_red_sandstone", new ResourceLocation("minecraft", "cut_red_sandstone")),
	RED_SANDSTONE_STAIRS("red_sandstone_stairs", new ResourceLocation("minecraft", "red_sandstone_stairs")),
	OAK_SLAB("oak_slab", new ResourceLocation("minecraft", "oak_slab")),
	SPRUCE_SLAB("spruce_slab", new ResourceLocation("minecraft", "spruce_slab")),
	BIRCH_SLAB("birch_slab", new ResourceLocation("minecraft", "birch_slab")),
	JUNGLE_SLAB("jungle_slab", new ResourceLocation("minecraft", "jungle_slab")),
	ACACIA_SLAB("acacia_slab", new ResourceLocation("minecraft", "acacia_slab")),
	DARK_OAK_SLAB("dark_oak_slab", new ResourceLocation("minecraft", "dark_oak_slab")),
	STONE_SLAB("stone_slab", new ResourceLocation("minecraft", "stone_slab")),
	SANDSTONE_SLAB("sandstone_slab", new ResourceLocation("minecraft", "sandstone_slab")),
	PETRIFIED_OAK_SLAB("petrified_oak_slab", new ResourceLocation("minecraft", "petrified_oak_slab")),
	COBBLESTONE_SLAB("cobblestone_slab", new ResourceLocation("minecraft", "cobblestone_slab")),
	BRICK_SLAB("brick_slab", new ResourceLocation("minecraft", "brick_slab")),
	STONE_BRICK_SLAB("stone_brick_slab", new ResourceLocation("minecraft", "stone_brick_slab")),
	NETHER_BRICK_SLAB("nether_brick_slab", new ResourceLocation("minecraft", "nether_brick_slab")),
	QUARTZ_SLAB("quartz_slab", new ResourceLocation("minecraft", "quartz_slab")),
	RED_SANDSTONE_SLAB("red_sandstone_slab", new ResourceLocation("minecraft", "red_sandstone_slab")),
	PURPUR_SLAB("purpur_slab", new ResourceLocation("minecraft", "purpur_slab")),
	SMOOTH_STONE("smooth_stone", new ResourceLocation("minecraft", "smooth_stone")),
	SMOOTH_SANDSTONE("smooth_sandstone", new ResourceLocation("minecraft", "smooth_sandstone")),
	SMOOTH_QUARTZ("smooth_quartz", new ResourceLocation("minecraft", "smooth_quartz")),
	SMOOTH_RED_SANDSTONE("smooth_red_sandstone", new ResourceLocation("minecraft", "smooth_red_sandstone")),
	SPRUCE_FENCE_GATE("spruce_fence_gate", new ResourceLocation("minecraft", "spruce_fence_gate")),
	BIRCH_FENCE_GATE("birch_fence_gate", new ResourceLocation("minecraft", "birch_fence_gate")),
	JUNGLE_FENCE_GATE("jungle_fence_gate", new ResourceLocation("minecraft", "jungle_fence_gate")),
	ACACIA_FENCE_GATE("acacia_fence_gate", new ResourceLocation("minecraft", "acacia_fence_gate")),
	DARK_OAK_FENCE_GATE("dark_oak_fence_gate", new ResourceLocation("minecraft", "dark_oak_fence_gate")),
	SPRUCE_FENCE("spruce_fence", new ResourceLocation("minecraft", "spruce_fence")),
	BIRCH_FENCE("birch_fence", new ResourceLocation("minecraft", "birch_fence")),
	JUNGLE_FENCE("jungle_fence", new ResourceLocation("minecraft", "jungle_fence")),
	ACACIA_FENCE("acacia_fence", new ResourceLocation("minecraft", "acacia_fence")),
	DARK_OAK_FENCE("dark_oak_fence", new ResourceLocation("minecraft", "dark_oak_fence")),
	SPRUCE_DOOR("spruce_door", new ResourceLocation("minecraft", "spruce_door")),
	BIRCH_DOOR("birch_door", new ResourceLocation("minecraft", "birch_door")),
	JUNGLE_DOOR("jungle_door", new ResourceLocation("minecraft", "jungle_door")),
	ACACIA_DOOR("acacia_door", new ResourceLocation("minecraft", "acacia_door")),
	DARK_OAK_DOOR("dark_oak_door", new ResourceLocation("minecraft", "dark_oak_door")),
	END_ROD("end_rod", new ResourceLocation("minecraft", "end_rod")),
	CHORUS_PLANT("chorus_plant", new ResourceLocation("minecraft", "chorus_plant")),
	CHORUS_FLOWER("chorus_flower", new ResourceLocation("minecraft", "chorus_flower")),
	PURPUR_BLOCK("purpur_block", new ResourceLocation("minecraft", "purpur_block")),
	PURPUR_PILLAR("purpur_pillar", new ResourceLocation("minecraft", "purpur_pillar")),
	PURPUR_STAIRS("purpur_stairs", new ResourceLocation("minecraft", "purpur_stairs")),
	END_STONE_BRICKS("end_stone_bricks", new ResourceLocation("minecraft", "end_stone_bricks")),
	BEETROOTS("beetroots", new ResourceLocation("minecraft", "beetroots")),
	GRASS_PATH("grass_path", new ResourceLocation("minecraft", "grass_path")),
	END_GATEWAY("end_gateway", new ResourceLocation("minecraft", "end_gateway")),
	REPEATING_COMMAND_BLOCK("repeating_command_block", new ResourceLocation("minecraft", "repeating_command_block")),
	CHAIN_COMMAND_BLOCK("chain_command_block", new ResourceLocation("minecraft", "chain_command_block")),
	FROSTED_ICE("frosted_ice", new ResourceLocation("minecraft", "frosted_ice")),
	MAGMA_BLOCK("magma_block", new ResourceLocation("minecraft", "magma_block")),
	NETHER_WART_BLOCK("nether_wart_block", new ResourceLocation("minecraft", "nether_wart_block")),
	RED_NETHER_BRICKS("red_nether_bricks", new ResourceLocation("minecraft", "red_nether_bricks")),
	BONE_BLOCK("bone_block", new ResourceLocation("minecraft", "bone_block")),
	STRUCTURE_VOID("structure_void", new ResourceLocation("minecraft", "structure_void")),
	OBSERVER("observer", new ResourceLocation("minecraft", "observer")),
	SHULKER_BOX("shulker_box", new ResourceLocation("minecraft", "shulker_box")),
	WHITE_SHULKER_BOX("white_shulker_box", new ResourceLocation("minecraft", "white_shulker_box")),
	ORANGE_SHULKER_BOX("orange_shulker_box", new ResourceLocation("minecraft", "orange_shulker_box")),
	MAGENTA_SHULKER_BOX("magenta_shulker_box", new ResourceLocation("minecraft", "magenta_shulker_box")),
	LIGHT_BLUE_SHULKER_BOX("light_blue_shulker_box", new ResourceLocation("minecraft", "light_blue_shulker_box")),
	YELLOW_SHULKER_BOX("yellow_shulker_box", new ResourceLocation("minecraft", "yellow_shulker_box")),
	LIME_SHULKER_BOX("lime_shulker_box", new ResourceLocation("minecraft", "lime_shulker_box")),
	PINK_SHULKER_BOX("pink_shulker_box", new ResourceLocation("minecraft", "pink_shulker_box")),
	GRAY_SHULKER_BOX("gray_shulker_box", new ResourceLocation("minecraft", "gray_shulker_box")),
	LIGHT_GRAY_SHULKER_BOX("light_gray_shulker_box", new ResourceLocation("minecraft", "light_gray_shulker_box")),
	CYAN_SHULKER_BOX("cyan_shulker_box", new ResourceLocation("minecraft", "cyan_shulker_box")),
	PURPLE_SHULKER_BOX("purple_shulker_box", new ResourceLocation("minecraft", "purple_shulker_box")),
	BLUE_SHULKER_BOX("blue_shulker_box", new ResourceLocation("minecraft", "blue_shulker_box")),
	BROWN_SHULKER_BOX("brown_shulker_box", new ResourceLocation("minecraft", "brown_shulker_box")),
	GREEN_SHULKER_BOX("green_shulker_box", new ResourceLocation("minecraft", "green_shulker_box")),
	RED_SHULKER_BOX("red_shulker_box", new ResourceLocation("minecraft", "red_shulker_box")),
	BLACK_SHULKER_BOX("black_shulker_box", new ResourceLocation("minecraft", "black_shulker_box")),
	WHITE_GLAZED_TERRACOTTA("white_glazed_terracotta", new ResourceLocation("minecraft", "white_glazed_terracotta")),
	ORANGE_GLAZED_TERRACOTTA("orange_glazed_terracotta", new ResourceLocation("minecraft", "orange_glazed_terracotta")),
	MAGENTA_GLAZED_TERRACOTTA("magenta_glazed_terracotta", new ResourceLocation("minecraft", "magenta_glazed_terracotta")),
	LIGHT_BLUE_GLAZED_TERRACOTTA("light_blue_glazed_terracotta", new ResourceLocation("minecraft", "light_blue_glazed_terracotta")),
	YELLOW_GLAZED_TERRACOTTA("yellow_glazed_terracotta", new ResourceLocation("minecraft", "yellow_glazed_terracotta")),
	LIME_GLAZED_TERRACOTTA("lime_glazed_terracotta", new ResourceLocation("minecraft", "lime_glazed_terracotta")),
	PINK_GLAZED_TERRACOTTA("pink_glazed_terracotta", new ResourceLocation("minecraft", "pink_glazed_terracotta")),
	GRAY_GLAZED_TERRACOTTA("gray_glazed_terracotta", new ResourceLocation("minecraft", "gray_glazed_terracotta")),
	LIGHT_GRAY_GLAZED_TERRACOTTA("light_gray_glazed_terracotta", new ResourceLocation("minecraft", "light_gray_glazed_terracotta")),
	CYAN_GLAZED_TERRACOTTA("cyan_glazed_terracotta", new ResourceLocation("minecraft", "cyan_glazed_terracotta")),
	PURPLE_GLAZED_TERRACOTTA("purple_glazed_terracotta", new ResourceLocation("minecraft", "purple_glazed_terracotta")),
	BLUE_GLAZED_TERRACOTTA("blue_glazed_terracotta", new ResourceLocation("minecraft", "blue_glazed_terracotta")),
	BROWN_GLAZED_TERRACOTTA("brown_glazed_terracotta", new ResourceLocation("minecraft", "brown_glazed_terracotta")),
	GREEN_GLAZED_TERRACOTTA("green_glazed_terracotta", new ResourceLocation("minecraft", "green_glazed_terracotta")),
	RED_GLAZED_TERRACOTTA("red_glazed_terracotta", new ResourceLocation("minecraft", "red_glazed_terracotta")),
	BLACK_GLAZED_TERRACOTTA("black_glazed_terracotta", new ResourceLocation("minecraft", "black_glazed_terracotta")),
	WHITE_CONCRETE("white_concrete", new ResourceLocation("minecraft", "white_concrete")),
	ORANGE_CONCRETE("orange_concrete", new ResourceLocation("minecraft", "orange_concrete")),
	MAGENTA_CONCRETE("magenta_concrete", new ResourceLocation("minecraft", "magenta_concrete")),
	LIGHT_BLUE_CONCRETE("light_blue_concrete", new ResourceLocation("minecraft", "light_blue_concrete")),
	YELLOW_CONCRETE("yellow_concrete", new ResourceLocation("minecraft", "yellow_concrete")),
	LIME_CONCRETE("lime_concrete", new ResourceLocation("minecraft", "lime_concrete")),
	PINK_CONCRETE("pink_concrete", new ResourceLocation("minecraft", "pink_concrete")),
	GRAY_CONCRETE("gray_concrete", new ResourceLocation("minecraft", "gray_concrete")),
	LIGHT_GRAY_CONCRETE("light_gray_concrete", new ResourceLocation("minecraft", "light_gray_concrete")),
	CYAN_CONCRETE("cyan_concrete", new ResourceLocation("minecraft", "cyan_concrete")),
	PURPLE_CONCRETE("purple_concrete", new ResourceLocation("minecraft", "purple_concrete")),
	BLUE_CONCRETE("blue_concrete", new ResourceLocation("minecraft", "blue_concrete")),
	BROWN_CONCRETE("brown_concrete", new ResourceLocation("minecraft", "brown_concrete")),
	GREEN_CONCRETE("green_concrete", new ResourceLocation("minecraft", "green_concrete")),
	RED_CONCRETE("red_concrete", new ResourceLocation("minecraft", "red_concrete")),
	BLACK_CONCRETE("black_concrete", new ResourceLocation("minecraft", "black_concrete")),
	WHITE_CONCRETE_POWDER("white_concrete_powder", new ResourceLocation("minecraft", "white_concrete_powder")),
	ORANGE_CONCRETE_POWDER("orange_concrete_powder", new ResourceLocation("minecraft", "orange_concrete_powder")),
	MAGENTA_CONCRETE_POWDER("magenta_concrete_powder", new ResourceLocation("minecraft", "magenta_concrete_powder")),
	LIGHT_BLUE_CONCRETE_POWDER("light_blue_concrete_powder", new ResourceLocation("minecraft", "light_blue_concrete_powder")),
	YELLOW_CONCRETE_POWDER("yellow_concrete_powder", new ResourceLocation("minecraft", "yellow_concrete_powder")),
	LIME_CONCRETE_POWDER("lime_concrete_powder", new ResourceLocation("minecraft", "lime_concrete_powder")),
	PINK_CONCRETE_POWDER("pink_concrete_powder", new ResourceLocation("minecraft", "pink_concrete_powder")),
	GRAY_CONCRETE_POWDER("gray_concrete_powder", new ResourceLocation("minecraft", "gray_concrete_powder")),
	LIGHT_GRAY_CONCRETE_POWDER("light_gray_concrete_powder", new ResourceLocation("minecraft", "light_gray_concrete_powder")),
	CYAN_CONCRETE_POWDER("cyan_concrete_powder", new ResourceLocation("minecraft", "cyan_concrete_powder")),
	PURPLE_CONCRETE_POWDER("purple_concrete_powder", new ResourceLocation("minecraft", "purple_concrete_powder")),
	BLUE_CONCRETE_POWDER("blue_concrete_powder", new ResourceLocation("minecraft", "blue_concrete_powder")),
	BROWN_CONCRETE_POWDER("brown_concrete_powder", new ResourceLocation("minecraft", "brown_concrete_powder")),
	GREEN_CONCRETE_POWDER("green_concrete_powder", new ResourceLocation("minecraft", "green_concrete_powder")),
	RED_CONCRETE_POWDER("red_concrete_powder", new ResourceLocation("minecraft", "red_concrete_powder")),
	BLACK_CONCRETE_POWDER("black_concrete_powder", new ResourceLocation("minecraft", "black_concrete_powder")),
	KELP("kelp", new ResourceLocation("minecraft", "kelp")),
	KELP_PLANT("kelp_plant", new ResourceLocation("minecraft", "kelp_plant")),
	DRIED_KELP_BLOCK("dried_kelp_block", new ResourceLocation("minecraft", "dried_kelp_block")),
	TURTLE_EGG("turtle_egg", new ResourceLocation("minecraft", "turtle_egg")),
	DEAD_TUBE_CORAL_BLOCK("dead_tube_coral_block", new ResourceLocation("minecraft", "dead_tube_coral_block")),
	DEAD_BRAIN_CORAL_BLOCK("dead_brain_coral_block", new ResourceLocation("minecraft", "dead_brain_coral_block")),
	DEAD_BUBBLE_CORAL_BLOCK("dead_bubble_coral_block", new ResourceLocation("minecraft", "dead_bubble_coral_block")),
	DEAD_FIRE_CORAL_BLOCK("dead_fire_coral_block", new ResourceLocation("minecraft", "dead_fire_coral_block")),
	DEAD_HORN_CORAL_BLOCK("dead_horn_coral_block", new ResourceLocation("minecraft", "dead_horn_coral_block")),
	TUBE_CORAL_BLOCK("tube_coral_block", new ResourceLocation("minecraft", "tube_coral_block")),
	BRAIN_CORAL_BLOCK("brain_coral_block", new ResourceLocation("minecraft", "brain_coral_block")),
	BUBBLE_CORAL_BLOCK("bubble_coral_block", new ResourceLocation("minecraft", "bubble_coral_block")),
	FIRE_CORAL_BLOCK("fire_coral_block", new ResourceLocation("minecraft", "fire_coral_block")),
	HORN_CORAL_BLOCK("horn_coral_block", new ResourceLocation("minecraft", "horn_coral_block")),
	DEAD_TUBE_CORAL("dead_tube_coral", new ResourceLocation("minecraft", "dead_tube_coral")),
	DEAD_BRAIN_CORAL("dead_brain_coral", new ResourceLocation("minecraft", "dead_brain_coral")),
	DEAD_BUBBLE_CORAL("dead_bubble_coral", new ResourceLocation("minecraft", "dead_bubble_coral")),
	DEAD_FIRE_CORAL("dead_fire_coral", new ResourceLocation("minecraft", "dead_fire_coral")),
	DEAD_HORN_CORAL("dead_horn_coral", new ResourceLocation("minecraft", "dead_horn_coral")),
	TUBE_CORAL("tube_coral", new ResourceLocation("minecraft", "tube_coral")),
	BRAIN_CORAL("brain_coral", new ResourceLocation("minecraft", "brain_coral")),
	BUBBLE_CORAL("bubble_coral", new ResourceLocation("minecraft", "bubble_coral")),
	FIRE_CORAL("fire_coral", new ResourceLocation("minecraft", "fire_coral")),
	HORN_CORAL("horn_coral", new ResourceLocation("minecraft", "horn_coral")),
	DEAD_TUBE_CORAL_WALL_FAN("dead_tube_coral_wall_fan", new ResourceLocation("minecraft", "dead_tube_coral_wall_fan")),
	DEAD_BRAIN_CORAL_WALL_FAN("dead_brain_coral_wall_fan", new ResourceLocation("minecraft", "dead_brain_coral_wall_fan")),
	DEAD_BUBBLE_CORAL_WALL_FAN("dead_bubble_coral_wall_fan", new ResourceLocation("minecraft", "dead_bubble_coral_wall_fan")),
	DEAD_FIRE_CORAL_WALL_FAN("dead_fire_coral_wall_fan", new ResourceLocation("minecraft", "dead_fire_coral_wall_fan")),
	DEAD_HORN_CORAL_WALL_FAN("dead_horn_coral_wall_fan", new ResourceLocation("minecraft", "dead_horn_coral_wall_fan")),
	TUBE_CORAL_WALL_FAN("tube_coral_wall_fan", new ResourceLocation("minecraft", "tube_coral_wall_fan")),
	BRAIN_CORAL_WALL_FAN("brain_coral_wall_fan", new ResourceLocation("minecraft", "brain_coral_wall_fan")),
	BUBBLE_CORAL_WALL_FAN("bubble_coral_wall_fan", new ResourceLocation("minecraft", "bubble_coral_wall_fan")),
	FIRE_CORAL_WALL_FAN("fire_coral_wall_fan", new ResourceLocation("minecraft", "fire_coral_wall_fan")),
	HORN_CORAL_WALL_FAN("horn_coral_wall_fan", new ResourceLocation("minecraft", "horn_coral_wall_fan")),
	DEAD_TUBE_CORAL_FAN("dead_tube_coral_fan", new ResourceLocation("minecraft", "dead_tube_coral_fan")),
	DEAD_BRAIN_CORAL_FAN("dead_brain_coral_fan", new ResourceLocation("minecraft", "dead_brain_coral_fan")),
	DEAD_BUBBLE_CORAL_FAN("dead_bubble_coral_fan", new ResourceLocation("minecraft", "dead_bubble_coral_fan")),
	DEAD_FIRE_CORAL_FAN("dead_fire_coral_fan", new ResourceLocation("minecraft", "dead_fire_coral_fan")),
	DEAD_HORN_CORAL_FAN("dead_horn_coral_fan", new ResourceLocation("minecraft", "dead_horn_coral_fan")),
	TUBE_CORAL_FAN("tube_coral_fan", new ResourceLocation("minecraft", "tube_coral_fan")),
	BRAIN_CORAL_FAN("brain_coral_fan", new ResourceLocation("minecraft", "brain_coral_fan")),
	BUBBLE_CORAL_FAN("bubble_coral_fan", new ResourceLocation("minecraft", "bubble_coral_fan")),
	FIRE_CORAL_FAN("fire_coral_fan", new ResourceLocation("minecraft", "fire_coral_fan")),
	HORN_CORAL_FAN("horn_coral_fan", new ResourceLocation("minecraft", "horn_coral_fan")),
	SEA_PICKLE("sea_pickle", new ResourceLocation("minecraft", "sea_pickle")),
	BLUE_ICE("blue_ice", new ResourceLocation("minecraft", "blue_ice")),
	CONDUIT("conduit", new ResourceLocation("minecraft", "conduit")),
	VOID_AIR("void_air", new ResourceLocation("minecraft", "void_air")),
	CAVE_AIR("cave_air", new ResourceLocation("minecraft", "cave_air")),
	BUBBLE_COLUMN("bubble_column", new ResourceLocation("minecraft", "bubble_column")),
	STRUCTURE_BLOCK("structure_block", new ResourceLocation("minecraft", "structure_block"));


    private String block_name;
    private Block block;

    Material(String block_name, ResourceLocation loc) //Material(String block_name, Block block)
    {
        this.block_name = block_name;
        //TODO
        this.block = IRegistry.BLOCK.getObject(loc);
    }

    public String getBlockName()
    {
        return block_name;
    }

    public Block getBlock()
    {
        return block;
    }

    /**
     * Static Members
     */

    public static Material getMaterialOfBlock(Block block)
    {
        for (Material material : values())
        {
            if (material.getBlock() == block)
            {
                return material;
            }
        }

        return Material.STONE;
    }

    public static Material getMaterialOfBlock(String block)
    {
        for (Material material : values())
        {
            if (material.getBlockName().equals(block))
            {
                return material;
            }
        }

        return Material.STONE;
    }
    public static String getNameOfBlock(Block block)
    {
        for (Material material : values())
        {
            if (material.getBlock() == block)
            {
                return material.getBlockName();
            }
        }

        return Material.STONE.getBlockName();
    }

    public static Block getNameOfBlock(String name)
    {
        for (Material material : values())
        {
            if (material.getBlockName().equalsIgnoreCase(name))
            {
                return material.getBlock();
            }
        }

        return Material.STONE.getBlock();
    }
}
